name: Actions worklflow

# on: [push]

# on: [pull_request] # this is for opened reopen and synchronised
# https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request

# on:
#   push:
#   pull_request:
#     types: [closed, assigned, opened, reopened]

# on:
#   schedule:
#     - cron: "*/5 * * * *" # minutes, hours, day of month, month, a day of week
#     - cron: "*/6 * * * *"

# on:
#   repository_dispatch: # trigger by POST request to some url with body containning event_type, empty will match all 
#     types: [build] # we need to send specific eventype. Inorder to authorize you need a token (besic auth with password)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment specification
        required: true
        type: string
        default: production

jobs:
  run-gitlab-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Echo default envs
        run: | 
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo "${{ github.token }}" 
          # git clone git@github:$GITHUB_REPOSITORY
          # git checkout $GITHUB_SHA
      - name: Clone repo
        uses: actions/checkout@v3
      - name: List files
        run: |
          pwd 
          ls -la
      - name: Simmplae js Actions
        id: greet
        uses: actions/hello-world-javascript-action@v1.1 # or branch (master) which is not recommended because breaking changes can be introduced or commitId
        with: # Action input
          who-to-greet: Michal
      - name: Log Greeting time
        run: echo "${{ steps.greet.outputs.time }}" # referencing ouput of action
      - name: Get inputs 
        run: echo ${{ inputs }}
