name: Container example 

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:13.5.0-alpine3.10
      # env:
      #   ENV: 1
      # ports:
      # volumes:
      # options: --cpus x --hostnames xx
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - name: Logg node version
        run: node -v
      - name: Step with docker container
        uses: docker://node:12.14.1-alpine3.10 # runs entrypoint of docker
        with: # we can provide etrypoint
          entrypoint: '/bin/echo' # ENTRYPOINT
          args: 'Hello world' # CMD
      - name: log node version
        uses: docker://node:12.14.1-alpine3.10 # runs entrypoint of docker
        with: # we can provide etrypoint
          entrypoint: '/usr/local/bin/node' # ENTRYPOINT
          args: '-v' # CMD
      - uses: actions/checkout@v1
      - name: Run a script
        uses: docker://node:12.14.1-alpine3.10 # runs entrypoint of docker
        with: # we can provide etrypoint
          entrypoint: './script.sh' # ENTRYPOINT
          args: 'This is custom arg' # CMD
