name: Container example 

on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container: 
      image: node:13.5.0-alpine3.10
      # env:
      #   ENV: 1
      # ports:
      # volumes:
      # options: --cpus x --hostnames xx
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release
