# strategy helps to setup env matrix ubuntu, win ... node versions, ...
name: Matrix
on: push
jobs:
  node_version:
    strategy:
      matrix:
        node_version: [6, 8, 10]
        os: [ macos-latest, ubuntu-latest, windows-latest ]
        exclude:
          - os: ubuntu-latest
            node_version: 6
          - os: macos-latest
            node_version: 8
        include: # helps to add extra variables to matrix config 
          - os: ubuntu-latest
            node_version: 4
            is_ubuntu: "true"
      # fail-fast: true # If one fails all will fail 
      # max-parallel: 0
    runs-on: ${{ matrix.os }}
    steps:
      - name: Log node version
        run: node -v
      - name: Change node version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log node version
        run: node -v
