name: Shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world" # Ubuntu and Mac have by default Bash and windows has Powershell
      - name: multiline script
        run: |
          python --version
          pip --version
      - name: echo debug secrets 
        run: | 
          echo $ACTIONS_RUNNER_DEBUG
          echo $ACTIONS_STEP_DEBUG