name: Shell commands

on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a string
        run: echo "Hello world" # Ubuntu and Mac have by default Bash and windows has Powershell
      - name: Multiline script
        run: |
          python --version
          pip --version
      - name: Echo debug secrets
        run: |
          echo $ACTIONS_RUNNER_DEBUG
          echo $ACTIONS_STEP_DEBUG
      - name: Python commans
        run: |
          import platform
          print(platform.processor())
        shell: python # override default shell
  run-windows-commands:
    runs-on: windows-latest
    steps:
      - name: Output current dir Powershell
        run: Get-Location
      - name: Output current dir Bash
        run: pwd
        shell: bash
